version: "3.8"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=myproject
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
            - POSTGRES_PORT=5432
    api:
        build:
            context: api
            dockerfile: Dockerfile
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./api:/api
        ports:
            - 8000:8000
        environment:
            - POSTGRES_DB=myproject
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
        depends_on:
            - db
    client:
        build:
            context: client
            dockerfile: Dockerfile
        volumes:
            - ./client:/client
        ports:
            - 8080:8080
        depends_on: 
            - api

volumes:
  postgres_db_data: