version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.6
      - image: circleci/postgres
        environment:
            - POSTGRES_DB=myproject
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
            - POSTGRES_PORT=5432

    working_directory: ~/api
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: python3 manage.py test