name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  full-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Builds application
        run: docker-compose --build

  back-end-test-check:
    runs-on: ubuntu-latest

    steps:
      - name: Tests
        run: docker-compose run api python3 manage.py test
