name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  full-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Builds application
        run: docker-compose build


  back-end-test-check:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: actions_db
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432

    env:
        POSTGRES_DB: actions_db
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.4'
      
      - name: Install requirements
        run: pip3 install -r api/requirements.txt

      - name: Migrate
        run: python3 api/manage.py migrate

      - name: Test
        run: python3 api/manage.py test

      - name: Lint
        run: pylint --load-plugins pylint_django --django-settings-module=api.settings api/*.py --fail-under=4


  front-end-test-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.1'

      - name: Test
        run: |
          yarn install
          yarn test:unit:ci
        working-directory: client/

      - name: Lint
        run: |
          yarn global add eslint
          yarn add eslint-plugin-vue
          yarn lint
        working-directory: client/


  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}